### PR TITLE
make gunicorn restart on chef runs

### LINKED ISSUE #32: Gunicorn does not restart on chef run
This caused an issue with gunicorn using an old version of Formsender until I ran `supervisorctl restart formsender`

### PR DESCRIPTION
**Pull request by tschuy**
fixes #32

### CODE REVIEW

**Comment by jordane** [comment]
What if we push a bad gunicorn config and crash it?

**Comment by tschuy** [comment]
What would be a better way to approach this, then? We can't just not restart the process. I'm not sure there is a **good** solution this, I think we just have to let it crash and hope people don't push bad code. Which is laughable.

**Comment by jordane** [comment]
@tschuy is there a configtest for gunicorn?

**Comment by tschuy** [comment]
None that I can find.

**Comment by jordane** [comment]
+1

**Pull request merged**
